name: Ubuntu build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "LICENSE.md"
      - ".gitignore"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "LICENSE.md"
      - ".gitignore"

permissions:
  contents: read

jobs:
  build:
    name: Ubuntu ${{matrix.arch}} with ${{matrix.dc}}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # If a particular matrix build fails, don't skip the rest.
      matrix:
        arch: ["x64", "x86"]
        dc: ["dmd-latest", "ldc-latest"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup D for development
        uses: dlang-community/setup-dlang@v1.3.0
        with:
          compiler: ${{matrix.dc}}

      - name: Install SDL2 dependencies
        run: |
          deps=""
          for dep in sdl2 sdl2-image sdl2-mixer sdl2-ttf; do
            deps="$deps lib${dep}-dev${apt_suffix}"
          done

          sudo apt update --fix-missing
          sudo apt upgrade -y

          echo Installing: $deps
          sudo apt install $deps -y

      - name: Build for SDL 2.0.0
        run: dub build

      - name: Test for SDL 2.0.0
        run: dub test

      - name: Build for SDL 2.0.1
        run: |
          dub build --d-version=SDL_201

      - name: Test for SDL 2.0.1
        run: |
          dub test --d-version=SDL_201

      - name: Build for SDL 2.0.2
        run: |
          dub build --d-version=SDL_202

      - name: Test for SDL 2.0.2
        run: |
          dub test --d-version=SDL_202

      - name: Build for SDL 2.0.3
        run: |
          dub build --d-version=SDL_203

      - name: Test for SDL 2.0.3
        run: |
          dub test --d-version=SDL_203

      - name: Build for SDL 2.0.4
        run: |
          dub build --d-version=SDL_204

      - name: Test for SDL 2.0.4
        run: |
          dub test --d-version=SDL_204

      - name: Build for SDL 2.0.5
        run: |
          dub build --d-version=SDL_205

      - name: Test for SDL 2.0.5
        run: |
          dub test --d-version=SDL_205

      - name: Build for SDL 2.0.6
        run: |
          dub build --d-version=SDL_206

      - name: Test for SDL 2.0.6
        run: |
          dub test --d-version=SDL_206

      - name: Build for SDL 2.0.7
        run: |
          dub build --d-version=SDL_207

      - name: Test for SDL 2.0.7
        run: |
          dub test --d-version=SDL_207

      - name: Build for SDL 2.0.8
        run: |
          dub build --d-version=SDL_208

      - name: Test for SDL 2.0.8
        run: |
          dub test --d-version=SDL_208

      - name: Build for SDL 2.0.9
        run: |
          dub build --d-version=SDL_209

      - name: Test for SDL 2.0.9
        run: |
          dub test --d-version=SDL_209

      - name: Build for SDL 2.0.10
        run: |
          dub build --d-version=SDL_2010

      - name: Test for SDL 2.0.10
        run: |
          dub test --d-version=SDL_2010

      - name: Build for SDL 2.0.12
        run: |
          dub build --d-version=SDL_2012

      - name: Test for SDL 2.0.12
        run: |
          dub test --d-version=SDL_2012

      - name: Build for SDL 2.0.14
        run: |
          dub build --d-version=SDL_2014

      - name: Test for SDL 2.0.14
        run: |
          dub test --d-version=SDL_2014

      - name: Build for SDL 2.0.16
        run: |
          dub build --d-version=SDL_2016

      - name: Test for SDL 2.0.16
        run: |
          dub test --d-version=SDL_2016

      - name: Build for SDL 2.0.18
        run: |
          dub build --d-version=SDL_2018

      - name: Test for SDL 2.0.18
        run: |
          dub test --d-version=SDL_2018

      - name: Build for SDL 2.0.20 (Maximum version in system)
        run: |
          dub build --d-version=SDL_2020

      - name: Test for SDL 2.0.20 (Maximum version in system)
        run: |
          dub test --d-version=SDL_2020

      - name: Build for SDL 2.0.22 (Not tested)
        run: |
          dub build --d-version=SDL_2022

      - name: Build for SDL 2.24 (Not tested)
        run: |
          dub build --d-version=SDL_2_24

      - name: Build for SDL 2.26 (Not tested)
        run: |
          dub build --d-version=SDL_2_26

      - name: Build for SDL 2.28 (Not tested)
        run: |
          dub build --d-version=SDL_2_28

      - name: Build for SDL 2.30 (Not tested)
        run: |
          dub build --d-version=SDL_2_30

      - name: Build for SDL_image 2.0.0
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_Image_200

      - name: Test for SDL_image 2.0.0
        run: |
          dub test --d-version=SDL_2020 --d-version=SDL_Image_200

      - name: Build for SDL_image 2.0.1
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_Image_201

      - name: Test for SDL_image 2.0.1
        run: |
          dub test --d-version=SDL_2020 --d-version=SDL_Image_201

      - name: Build for SDL_image 2.0.2
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_Image_202

      - name: Test for SDL_image 2.0.2
        run: |
          dub test --d-version=SDL_2020 --d-version=SDL_Image_202

      - name: Build for SDL_image 2.0.3
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_Image_203

      - name: Test for SDL_image 2.0.3
        run: |
          dub test --d-version=SDL_2020 --d-version=SDL_Image_203

      - name: Build for SDL_image 2.0.4
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_Image_204

      - name: Test for SDL_image 2.0.4
        run: |
          dub test --d-version=SDL_2020 --d-version=SDL_Image_204

      - name: Build for SDL_image 2.0.5 (Maximum version in system)
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_Image_205

      - name: Test for SDL_image 2.0.5 (Maximum version in system)
        run: |
          dub test --d-version=SDL_2020 --d-version=SDL_Image_205

      - name: Build for SDL_image 2.6 (Not tested)
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_Image_2_6

      - name: Build for SDL_image 2.8 (Not tested)
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_Image_2_8

      - name: Build for SDL_mixer 2.0.0
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_Mixer_200

      - name: Test for SDL_mixer 2.0.0
        run: |
          dub test --d-version=SDL_2020 --d-version=SDL_Mixer_200

      - name: Build for SDL_mixer 2.0.1
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_Mixer_201

      - name: Test for SDL_mixer 2.0.1
        run: |
          dub test --d-version=SDL_2020 --d-version=SDL_Mixer_201

      - name: Build for SDL_mixer 2.0.2
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_Mixer_202

      - name: Test for SDL_mixer 2.0.2
        run: |
          dub test --d-version=SDL_2020 --d-version=SDL_Mixer_202

      - name: Build for SDL_mixer 2.0.4 (Maximum version in system)
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_Mixer_204

      - name: Test for SDL_mixer 2.0.4 (Maximum version in system)
        run: |
          dub test --d-version=SDL_2020 --d-version=SDL_Mixer_204

      - name: Build for SDL_mixer 2.6 (Not tested)
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_Mixer_2_6

      - name: Build for SDL_mixer 2.8 (Not tested)
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_Mixer_2_8

      - name: Build for SDL_ttf 2.0.12
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_TTF_2012

      - name: Test for SDL_ttf 2.0.12
        run: |
          dub test --d-version=SDL_2020 --d-version=SDL_TTF_2012

      - name: Build for SDL_ttf 2.0.13
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_TTF_2013

      - name: Test for SDL_ttf 2.0.13
        run: |
          dub test --d-version=SDL_2020 --d-version=SDL_TTF_2013

      - name: Build for SDL_ttf 2.0.14
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_TTF_2014

      - name: Test for SDL_ttf 2.0.14
        run: |
          dub test --d-version=SDL_2020 --d-version=SDL_TTF_2014

      - name: Build for SDL_ttf 2.0.15
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_TTF_2015

      - name: Test for SDL_ttf 2.0.15
        run: |
          dub test --d-version=SDL_2020 --d-version=SDL_TTF_2015

      - name: Build for SDL_ttf 2.0.18 (Maximum version in system)
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_TTF_2018

      - name: Test for SDL_ttf 2.0.18 (Maximum version in system)
        run: |
          dub test --d-version=SDL_2020 --d-version=SDL_TTF_2018

      - name: Build for SDL_ttf 2.20 (Not tested)
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_TTF_2_20

      - name: Build for SDL_ttf 2.22 (Not tested)
        run: |
          dub build --d-version=SDL_2_30 --d-version=SDL_TTF_2_22

      - name: Generate ddox
        run: |
          if [[ "${{matrix.dc}}" == "dmd-latest" ]]; then
            dub build -b ddox
          else
            echo Step skipped.
          fi

      - name: Build examples
        run: |
          for folder in examples/*; do
            if [ -d "$folder" ]; then
              cd $folder
              echo Building $folder...
              dub build
              cd ../..
            fi
          done
